### ISSUE TITLE
Wireless tutorial - discussion

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet-tutorials#1]
Lets's discuss the wireless tutorial. What is not clear, how it could be enhanced,

**Comment by nfarha** [comment]
Hi Rudy, 
Ive download the inet 3.6 and omnet 5.1 using window 7 platform. here I found 3 error with the wireless tutorial results for wireless 8,9 and 10

![error log](https://user-images.githubusercontent.com/22759937/30996622-b5838726-a4f4-11e7-91a9-96348c06440a.jpg)

**Comment by applebujji** [comment]
In INET tutorial , I am doing 3rd problem that is Wireless A in folder wireless of tutorial there mentioned that node can pass the data to its communication range only but packets are along the whole network.

**Comment by applebujji** [comment]
can you please tell me how to restrict packet passing to particular range

**Comment by adamgeorge309** [comment]
There is a misunderstanding here. Both the expanding transmission disk and the red arrow animation reach all nodes, but that doesn't mean that nodes outside of the communication range actually receive the packet. The green dotted arrows indicate successful packet reception at the physical layer (which, as you can see, are displayed only for nodes within the communication range. In other words, the communication range works as expected.

**Comment by ManiAm** [comment]
Wireless Tutorial Step 1:

The AckingWirelessInterface uses the 'AckingMac' as its mac and 'UnitDiskRadio' as its radio. When 'useAck' parameter is false, then the data-link layer has no flow control. 

![111](https://user-images.githubusercontent.com/5473998/37801060-52b6e760-2de2-11e8-8f67-35cd27283eae.png)

When 'useAck' parameter is true, then I was expecting to see the stop-and-wait flow control. The sender sends one frame, stops until it receives confirmation (ack) from the receiver, and then sends the next.

![222](https://user-images.githubusercontent.com/5473998/37801063-58232894-2de2-11e8-92b1-4e799f8b1460.png)

but I was wrong. I do not know why ack is implemented 'out of bound' and second why the sender does not wait for the receiver's ack.

**Comment by levy** [comment]
The reason is that the AckingMac module is a simplistic model. If you look at its NED documentation, it clearly states that it uses out of bound ACKs. It doesn't support frame retransmission at all, the ACK is only useful for statistics and link break signals. The sender MAC simply waits until the ACK timeout expires to decide whether the frame was acknowledged or not. So basically it does what your second picture shows, except the ACK frames are not known to the PHY modules and thus they are not represented on the physical medium.

**Comment by levy** [comment]
While what you are suggesting makes sense in various ways, this would be a lot of work for which we do not have the necessary human resources.

**Comment by amedo990** [comment]
Hello,
I have tried the wireless tutorial with: INET-3.5.0 and OMNeT++ 5.1 using window 10. The simulation can't starts and gives the following error :
![captur3e](https://user-images.githubusercontent.com/19344945/40315760-908545be-5d1c-11e8-9afd-1b29676c66e3.PNG)

**Comment by kashiakashia** [comment]
Hi guys! I've been struggling for a couple of months already with the 8th case in the tutorial ([Config Wireless08], description = Modeling energy consumption).
The` energyBalance` variable is empty when I run simulation on my computer. So are of course `residualCapacity` vectors.
![image](https://user-images.githubusercontent.com/37773120/41597460-cd494cd0-73cd-11e8-8a36-6dab37012b58.png)
I really don't know what is wrong, I simply copied the code from a tutorial, and everything has been working up to this moment.
I would appriciate your help!

**Comment by adamgeorge309** [comment]
Thanks for reporting this! The issue with the energyBalance being NaN is already fixed in the upcoming INET 4.0 release.

**Comment by adamgeorge309** [comment]
What INET version are you using? Could you please try it with OMNeT++ 5.4 and INET 3.6.4 and see if it works?

**Comment by kashiakashia** [comment]
@adamgeorge309 thank you so much for your fast reply. I use inet-3.6.3 version on Omnet++ 5.2.
Yes, I can install higer version, if it is recommended. I will install it and get back to you, to let you know, how it works. Thanks again!

**Comment by kashiakashia** [comment]
@adamgeorge309 I installed the newest version and tryed it again. Unfortunately, I still get the same error. `EnergyBalance` and `ResidualCapacity Vector` are empty. Is there any way to fix this problem?
<img width="662" alt="przechwytywanie" src="https://user-images.githubusercontent.com/37773120/41663371-93937476-74a3-11e8-996b-6d9a6c8d7a19.PNG">
<img width="624" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/37773120/41663378-979512c8-74a3-11e8-919f-343b1b959e0b.PNG">

* I made a test on Omnetpp 5.4 and inet-3.6.4

**Comment by adamgeorge309** [comment]
You should try adding record=last to the ResidualEnergyCapacity statistic in EpEnergyStorageBase.ned (so its `record=vector,last;` instead of `record=vector;`). I hope this fixes it :)

**Comment by kashiakashia** [comment]
Thank you, @adamgeorge309 .I followed your instruction, unfortunately it is stil not working :( I changed the file under path` /inet/src/inet/power/base/EpEnergyStorageBase.ned` and changed the line into `@statistic[residualEnergyCapacity](title="Residual energy capacity"; source=residualEnergyCapacityChanged; record=vector, last; interpolationmode=linear);`. What I get right now is
![image](https://user-images.githubusercontent.com/37773120/41710998-50133408-7547-11e8-8b9d-1e8d6e5a488f.png)

**Comment by kashiakashia** [comment]
what is strange, `ResidualCapacity` vector works properly in the example under path	/inet/examples/wireless/power/omnetpp.ini
![image](https://user-images.githubusercontent.com/37773120/41712870-e8a75eca-754b-11e8-95e4-1fbe7c6ea9eb.png)

**Comment by adamgeorge309** [comment]
The power example uses SimpleEpEnergyStorage, where the issue is not present. The issue with IdealEpEnergyStorage is already fixed in the Integration branch in INET. You could use that with omnetpp 5.4.

Or alternatively apply this patch that fixes it:
https://github.com/inet-framework/inet/commit/97d2ae58726f4d0a7bdb76818517e1fa994b6e8f

**Comment by kashiakashia** [comment]
Thank you so much with helping me! Now all works fine! :)
![image](https://user-images.githubusercontent.com/37773120/41719265-da4b31ee-755f-11e8-9522-1f5441c7df05.png)
I downloaded newest version of INET via omnet  5.4 and it is written that the version is inet-3.6.4-394571f. However my file were different from those in your repository (inet-framework/inet@97d2ae5). My version didn't have the new lines you added.
I assume I still don't have newest version of INET. Should I download it manually?

**Comment by kashiakashia** [comment]
I downloaded newest stable version from https://inet.omnetpp.org/Download.html and checked manually the files - they are different from those in the repository you've send me.
Is there any place I can download the full "fixed" version of INET?

**Comment by adamgeorge309** [comment]
You could add the few missing lines to IdealEpEnergyStorage.cc and EpEnergyStorageBase.h manually :)

Or...there are development releases of the upcoming 4.0, e.g. 3.99.3:
https://github.com/inet-framework/inet/releases/download/v3.99.3/inet-3.99.3-src.tgz

Or you could clone the INET repo from github and use the Integration branch.
Note that there are major changes in the 4.0 version, some module names might be different.

**Comment by kashiakashia** [comment]
Thank you :) now all is clear!

**Comment by thihakyawjob** [comment]
Hi,

How do you plot the bitErrorRate in wireless 13?

Please guide me.

I can't find Chart:bitErrorRate:vector file. I only saw histogram file.

Thanks.

Regards,
Thiha

**Comment by thihakyawjob** [comment]
Hi,

How can I plot below picture from wireless tutorial [Config Wireless13].
![wireless-step13](https://user-images.githubusercontent.com/12581592/42388102-011c3f2a-8177-11e8-8873-6c93a3f40ea9.png)

I have simulated for 
*.radioMedium.pathLoss.typename = "FreeSpacePathLoss"
*.radioMedium.pathLoss.typename = "TwoRayGroundReflection"

But I still don't know how to plot it.

Thanks.
Regards,
Thiha Kyaw

**Comment by George425** [comment]
Having trouble generating the graph made in Step 7. The UdpSink will not output the vector for Packet Sequence numbers received, all other results are fine. Any suggestions?

**Comment by nagasai007** [comment]
Why did you use AODV network, why not DSDV?, DSR?
& Why did you use UDP as transfer protocol, why not TCP?

**Comment by rhornig** [comment]
There is no particular reason why we choose AODV or UDP. They are just simple enough to show the basics. Anything else besides the main point of a tutorial should be kept as simple as possible (but no simpler :)

**Comment by BiswaranjanNITR** [comment]
Upto configuring node movements it is working. But while configuring adhoc routing ini file is running. Node movement is also there. But there is no packet transmission. I am not able to find the reason for this. Kindly suggest regarding this.

**Comment by hendkhalifa** [comment]
I need to implement DSR routing protocol with omnetpp5.4.1 and inet4 but i can't find him?
How can i do this , please ?

**Comment by edlongman** [comment]
I've noticed that this Tutorial still refers to `AckingWirelessNic ` etc. 

Should this not be `AckingWirelessInterface`?

I could make a pull req for this change if that's best. Possibly this will incorporate other updates to references to `Nic`

**Comment by levy** [comment]
Yes, it should be changed. I guess @adamgeorge309 will take care of it, but thanks for notifying us.

**Comment by adamgeorge309** [comment]
It's fixed now, thanks for pointing this out.

**Comment by edlongman** [comment]
It's worth saying that this is a problem that percolates through quite a
lot of the inet docs because of the changes of Nic

This commit changes some example:
https://github.com/inet-framework/inet/commit/3c3e6f8dab832be806d8c3bcbef889019a4636ec
But I found references to "Ideal Radio" in the tutorials, Shouldn't it be
UnitDiskRadio

https://github.com/inet-framework/inet-tutorials/blob/a4e48ad7fab49ad6521e8ed6ea0bdace295d596a/wireless/omnetpp.ini.commented#L38
and
https://github.com/inet-framework/inet-tutorials/blob/a4e48ad7fab49ad6521e8ed6ea0bdace295d596a/wireless/omnetpp.ini.commented#L157

See the change log:
https://github.com/inet-framework/inet/blob/3fb8626aee65891971bb5cb7948dcc9e500ea4fd/src/inet/physicallayer/unitdisk/ChangeLog#L44

Sorry to be pedantic!

**Comment by levy** [comment]
You're absolutely right, these should be fixed too.

**Comment by adamgeorge309** [comment]
Done, there shouldn't be any more references to outdated module names in the tutorials anymore. Thanks again for finding them.

**Comment by PeiZhonghui** [comment]
> 嗨，
> 
> 如何在无线教程[Config Wireless13]下面绘制下图。
> ![无线步骤13](https://user-images.githubusercontent.com/12581592/42388102-011c3f2a-8177-11e8-8873-6c93a3f40ea9.png)
> 
> 我已经模拟了
> * .radioMedium.pathLoss.typename =“FreeSpacePathLoss” 
> * .radioMedium.pathLoss.typename =“TwoRayGroundReflection”
> 
> 但我仍然不知道如何绘制它。
> 
> 谢谢。
> 此致，
> Thiha Kyaw

Hello, I encountered the same problem with thihakyawjob in wireless13. I manually added the bit error rate vector signal record, but the picture I drew was not the same as the one in the tutorial. Do you have any good suggestions, thank you.
![image](https://user-images.githubusercontent.com/47771830/53061748-956d9a80-34f9-11e9-97ae-03dab912fe53.png)

**Comment by PeiZhonghui** [comment]
> Hi,
> 
> How can I plot below picture from wireless tutorial [Config Wireless13].
> ![wireless-step13](https://user-images.githubusercontent.com/12581592/42388102-011c3f2a-8177-11e8-8873-6c93a3f40ea9.png)
> 
> I have simulated for
> *.radioMedium.pathLoss.typename = "FreeSpacePathLoss"
> *.radioMedium.pathLoss.typename = "TwoRayGroundReflection"
> 
> But I still don't know how to plot it.
> 
> Thanks.
> Regards,
> Thiha Kyaw

Hello, I encountered the same problem with thihakyawjob in wireless13. I manually added the bit error rate vector signal record, but the picture I drew was not the same as the one in the tutorial. Do you have any good suggestions, thank you.
![image](https://user-images.githubusercontent.com/47771830/53061845-e087ad80-34f9-11e9-9f2b-6a2acbc57949.png)

**Comment by adamgeorge309** [comment]
The bitErrorRate vector is not being recorded. You need to put this line in Step12 in omnetpp.ini:
`*.hostR1.wlan[*].radio.bitErrorRate.result-recording-modes = default,+vector`
This turns on vector recording for the bitErrorRate in hostR1.
You also have to zoom in on the chart to get the same result as on the image. This will be fixed in an upcoming release (and in the tutorials master branch momentarily :)

**Comment by adamgeorge309** [comment]
> Having trouble generating the graph made in Step 7. The UdpSink will not output the vector for Packet Sequence numbers received, all other results are fine. Any suggestions?

The result filter for this statistic was not working, it's fixed now in the INET master branch. 
([fixed by this commit](https://github.com/inet-framework/inet/commit/0aa730d045e84d244a65929bbb199611aeb742da))

Thanks for the report!

**Comment by samikov** [comment]
Hi everyone,
how i can make the below figure tag ( packet received: 0 ) incrément the number of packet received . I wrote her own code as in the tutorial , but to no avail
Thank all
![Capture](https://user-images.githubusercontent.com/51828208/59519295-77201600-8ebf-11e9-8ec4-c99d9eb1802b.PNG)
